// Shared cache + compute path for the daily-picks board. Lives here (not in route.ts)
// because Next.js disallows arbitrary exports from route files.
//
// IMPORTANT: the in-memory Map below ONLY works inside a single Vercel function instance.
// Vercel scales horizontally — multiple instances mean a slate generated by one isn't seen
// by another. So we ALSO persist the slate to Postgres (himothy_daily_slate_cache table)
// keyed by ET-date + board. The Postgres layer is what makes the frozen-slate rule actually
// hold across the day. In-memory is just the fast-path for back-to-back hits on the same
// instance.

import { runDailyDeepResearch, type BoardType } from '@/services/deepResearchService';
import { getOddsInsightForPick, getTotalsInsightForPick, hasOddsApi } from '@/services/oddsApiService';
import { getOddsBucketStats } from '@/services/pickRegistryService';
import { oddsBucket } from '@/lib/oddsBucket';
import { hasDatabase } from '@/lib/hasDatabase';
import { prisma } from '@/lib/prisma';

export const boardCache = new Map<string, { data: any; generatedAt: number }>();

let _slateCacheSchemaReady = false;
async function ensureSlateCacheSchema() {
  if (_slateCacheSchemaReady || !hasDatabase()) return;
  try {
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "DailySlateCache" (
        "version" TEXT NOT NULL,
        "etDate" TEXT NOT NULL,
        "board" TEXT NOT NULL,
        "data" JSONB NOT NULL,
        "generatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY ("version", "etDate", "board")
      )
    `);
    _slateCacheSchemaReady = true;
  } catch (err) {
    console.error('[dailyBoardCache] ensureSlateCacheSchema failed', err);
  }
}

// FROZEN = IMMUTABLE. Read the day's board regardless of which rules-version froze it. This
// is what makes "lock once recorded" hold: once ANY version has frozen today's board, every
// later request — even after a deploy that bumps SLATE_RULES_VERSION — serves that exact
// board instead of recomputing a different one (which is how the record drifted from the
// display). A version bump therefore only affects the NEXT ET-day, never a posted slate.
async function readPersistedSlate(etDate: string, board: string): Promise<any | null> {
  if (!hasDatabase()) return null;
  await ensureSlateCacheSchema();
  try {
    const rows = await prisma.$queryRawUnsafe<any[]>(
      `SELECT "data" FROM "DailySlateCache" WHERE "etDate" = $1 AND "board" = $2 ORDER BY "generatedAt" DESC LIMIT 1`,
      etDate, board,
    );
    return rows[0]?.data ?? null;
  } catch (err) {
    console.error('[dailyBoardCache] readPersistedSlate failed', err);
    return null;
  }
}

// WRITE-ONCE per ET-day+board. ON CONFLICT DO NOTHING (not DO UPDATE) so a posted slate is
// never silently overwritten by a later recompute. To intentionally replace it, an admin
// must first delete it (deletePersistedSlate) — the explicit hard-reset escape hatch.
async function writePersistedSlate(version: string, etDate: string, board: string, data: any) {
  if (!hasDatabase()) return;
  await ensureSlateCacheSchema();
  try {
    // Guard against replacing a board already frozen under a DIFFERENT version this ET-day.
    const existing = await readPersistedSlate(etDate, board);
    if (existing) return;
    await prisma.$executeRawUnsafe(
      `INSERT INTO "DailySlateCache" ("version", "etDate", "board", "data", "generatedAt")
       VALUES ($1, $2, $3, $4::jsonb, NOW())
       ON CONFLICT ("version", "etDate", "board") DO NOTHING`,
      version, etDate, board, JSON.stringify(data),
    );
  } catch (err) {
    console.error('[dailyBoardCache] writePersistedSlate failed', err);
  }
}

// Hard reset (admin only): clears EVERY version of the day's board so the next compute can
// post a fresh one. This is the single sanctioned way to change a posted slate mid-day.
async function deletePersistedSlate(etDate: string, board: string) {
  if (!hasDatabase()) return;
  try {
    await prisma.$executeRawUnsafe(
      `DELETE FROM "DailySlateCache" WHERE "etDate" = $1 AND "board" = $2`,
      etDate, board,
    );
  } catch (err) {
    console.error('[dailyBoardCache] deletePersistedSlate failed', err);
  }
}
// CACHE_TTL_MS kept for back-compat (some callers still reference it) but no longer used
// to expire entries mid-day — see slateVersionKey below for the freeze model.
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

// Bump this when the slate-selection rules change (e.g., today-only filter) so any cached
// board from a previous algorithm doesn't survive.
const SLATE_RULES_VERSION = 'frozen-v1';

// ET-anchored date string in YYYYMMDD form. Each ET-day gets its own cache entry so the
// slate snapshot from the morning's 8am ET cron lives ALL DAY until the next ET-day's
// cron generates a fresh one. Mid-day requests always read the frozen snapshot — never
// re-generate — which means finished games stay on the slate exactly as published.
function todayEtKey(): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(new Date());
  return `${parts.find((p) => p.type === 'year')?.value}${parts.find((p) => p.type === 'month')?.value}${parts.find((p) => p.type === 'day')?.value}`;
}

function slateVersionKey(board: string) {
  return `${SLATE_RULES_VERSION}|${todayEtKey()}|${board}`;
}

// Generic per-ET-day FREEZE for any keyed computation (e.g. sport-parlays, power20). Same
// model as the main board: compute once per ET-day, persist to Postgres so every Vercel
// instance serves the SAME frozen result all day — so these "posted picks" don't shift
// mid-day. Pass force=true (admin only) to regenerate.
export async function getFrozenDaily(key: string, compute: () => Promise<any>, force = false): Promise<any> {
  const etDate = todayEtKey();
  const memKey = `${SLATE_RULES_VERSION}|${etDate}|${key}`;
  if (!force) {
    const mem = boardCache.get(memKey);
    if (mem) return mem.data;
    const persisted = await readPersistedSlate(etDate, key);
    if (persisted) { boardCache.set(memKey, { data: persisted, generatedAt: Date.now() }); return persisted; }
  }
  const data = await compute();
  boardCache.set(memKey, { data, generatedAt: Date.now() });
  await writePersistedSlate(SLATE_RULES_VERSION, etDate, key, data);
  return data;
}

async function enrichWithBucketStats(result: any) {
  if (!hasDatabase() || !result) return result;
  try {
    const stats = await getOddsBucketStats();
    const tag = (p: any) => {
      if (!p?.odds) return;
      const bucket = oddsBucket(p.odds);
      if (!bucket) return;
      const s = stats[bucket];
      p.bucketStats = { bucket, ...(s || { wins: 0, losses: 0, pushes: 0, total: 0, winRate: '0%' }) };
    };
    if (result.grandSlam) tag(result.grandSlam);
    for (const key of ['pressurePack', 'vip4Pack', 'parlayPlan', 'marquee']) {
      for (const p of result[key] || []) tag(p);
    }
  } catch { /* non-blocking */ }
  return result;
}

async function enrichWithOdds(result: any) {
  if (!hasOddsApi() || !result) return result;
  const one = async (p: any) => {
    if (!p?.league || !p?.homeTeam?.name || !p?.awayTeam?.name || !p?.selectionSide) return;
    try {
      p.oddsInsight = await getOddsInsightForPick(p.league, p.awayTeam.name, p.homeTeam.name, p.selectionSide);
    } catch { /* non-blocking */ }
    if (p.marketType === 'total') {
      try {
        p.totalsInsight = await getTotalsInsightForPick(p.league, p.awayTeam.name, p.homeTeam.name);
      } catch { /* non-blocking */ }
    }
  };
  if (result.grandSlam) await one(result.grandSlam);
  for (const key of ['pressurePack', 'vip4Pack', 'parlayPlan', 'marquee']) {
    for (const p of result[key] || []) await one(p);
  }
  return result;
}

// BEST-MARKET-PER-GAME: for each featured pick, check EVERY market we can price on that game
// (full total, team totals, halves, quarters, hockey periods, F5) and publish whichever has
// the HIGHEST confidence — not just the moneyline/run line. Per the owner: don't be lazy and
// default to the ML/spread; if a total or team total in the game scores higher, that's the
// play. We only keep the side/run line when nothing else beats it by the margin.
// FLOOR is a basic-credibility gate (don't swap into a no-edge total); MARGIN avoids flipping
// on noise. Was 75/4, which hid genuinely-stronger 68–74 totals behind a moneyline — lowered
// so the best market actually wins.
async function enrichWithBestMarket(result: any) {
  if (!hasOddsApi() || !result) return result;
  const FLOOR = 58;     // a totals-family play just needs a real edge (base score is 55)
  const MARGIN = 3;     // and clearly beat the current pick's confidence
  let buildBestMarketSwap: (p: any, opts?: { includeProps?: boolean }) => Promise<any>;
  try {
    ({ buildBestMarketSwap } = await import('@/services/deepResearchService'));
  } catch { return result; }
  const consider = async (p: any) => {
    if (!p) return;
    try {
      // Dig player props too when this play needs lifting — a Big Game / marquee pick or
      // anything still under 82. Bounded so prop fetches don't run on the whole slate.
      const includeProps = Boolean(p.bigGameLabel) || (p.confidenceScore ?? 0) < 82;
      const best = await buildBestMarketSwap(p, { includeProps });
      if (!best) return;
      if (best.confidence < FLOOR) return;
      if (best.confidence <= (p.confidenceScore ?? 0) + MARGIN) return;
      if (best.marketType === p.marketType && best.selection === p.selection) return;
      p.selection = best.selection;
      p.marketType = best.marketType;
      p.selectionSide = best.selectionSide;
      p.odds = best.odds;
      p.line = best.line;
      p.confidenceScore = best.confidence;
      p.bestMarketDetail = best.detail;
    } catch { /* non-blocking */ }
  };
  if (result.grandSlam) await consider(result.grandSlam);
  for (const key of ['pressurePack', 'vip4Pack', 'parlayPlan', 'marquee']) {
    await Promise.all((result[key] || []).map((p: any) => consider(p)));
  }
  return result;
}

// VALUE RANKING: within each multi-pick product, float the plays where our price beats the
// market (positive valueEdge) to the top, then by confidence. Doesn't add/remove picks —
// keeps the full slate, just leads with the best-priced plays.
function rankByValue(result: any) {
  if (!result) return result;
  const valOf = (p: any) => (typeof p?.oddsInsight?.valueEdge === 'number' ? p.oddsInsight.valueEdge : -999);
  const confOf = (p: any) => (typeof p?.confidenceScore === 'number' ? p.confidenceScore : 0);
  for (const key of ['pressurePack', 'vip4Pack', 'parlayPlan']) {
    if (Array.isArray(result[key])) {
      result[key].sort((a: any, b: any) => (valOf(b) - valOf(a)) || (confOf(b) - confOf(a)));
    }
  }
  return result;
}

function flattenBoardPicks(data: any): any[] {
  const arr: any[] = [];
  if (!data) return arr;
  if (data.grandSlam) arr.push(data.grandSlam);
  for (const k of ['pressurePack', 'vip4Pack', 'parlayPlan', 'marquee', 'nrfi']) {
    for (const p of data[k] || []) arr.push(p);
  }
  return arr;
}

export function getCachedBoardPicks(board: string): any[] {
  const c = boardCache.get(slateVersionKey(board));
  return c ? flattenBoardPicks(c.data) : [];
}

export async function invalidateBoardCache(board: string) {
  boardCache.delete(slateVersionKey(board));
  await deletePersistedSlate(todayEtKey(), board);
}

export function getCachedBoard(board: string) {
  return boardCache.get(slateVersionKey(board));
}

// Read the frozen slate persisted for a SPECIFIC past ET date (any rules version) — used
// by the registry recovery to record/grade picks from boards that were published but never
// made it into the registry. Returns the stored BoardPicksResult or null.
export async function getPersistedBoardForDate(etDate: string, board: string): Promise<any | null> {
  if (!hasDatabase()) return null;
  await ensureSlateCacheSchema();
  try {
    const rows = await prisma.$queryRawUnsafe<Array<{ data: any }>>(
      `SELECT "data" FROM "DailySlateCache" WHERE "etDate" = $1 AND "board" = $2 ORDER BY "generatedAt" DESC LIMIT 1`,
      etDate, board,
    );
    if (!rows[0]?.data) return null;
    return typeof rows[0].data === 'string' ? JSON.parse(rows[0].data) : rows[0].data;
  } catch {
    return null;
  }
}

export async function getOrComputeBoard(board: BoardType): Promise<any> {
  const etDate = todayEtKey();
  const key = `${SLATE_RULES_VERSION}|${etDate}|${board}`;

  // FROZEN SLATE — three-layer lookup:
  // 1. In-memory cache on this Vercel function instance (fastest)
  // 2. Postgres-persisted slate keyed by ET-date + board (survives instance churn)
  // 3. Compute fresh + persist (first hit of the ET-day, or after explicit invalidate)
  const mem = boardCache.get(key);
  if (mem) return mem.data;

  const persisted = await readPersistedSlate(etDate, board);
  if (persisted) {
    boardCache.set(key, { data: persisted, generatedAt: Date.now() });
    return persisted;
  }

  const result = await runDailyDeepResearch(board);
  await enrichWithOdds(result);
  // Swap a featured pick to its best totals-family market (total/team total/half/F5) when
  // that's clearly the stronger play, then float the best-priced plays to the top.
  await enrichWithBestMarket(result);
  rankByValue(result);
  await enrichWithBucketStats(result);
  const valuePool: any[] = [result.grandSlam, ...(result.pressurePack || []), ...(result.vip4Pack || []), ...(result.parlayPlan || []), ...(result.marquee || [])].filter(Boolean);
  (result as any).valuePlays = valuePool
    .filter((p: any) => p.marketType === 'moneyline' && p.oddsInsight && typeof p.oddsInsight.valueEdge === 'number' && p.oddsInsight.valueEdge > 0)
    .sort((a: any, b: any) => b.oddsInsight.valueEdge - a.oddsInsight.valueEdge);
  boardCache.set(key, { data: result, generatedAt: Date.now() });
  // Persist so the next function instance reads the same slate (otherwise the slate is
  // NOT actually frozen — each cold instance regenerates with possibly different picks).
  await writePersistedSlate(SLATE_RULES_VERSION, etDate, board, result);

  // INLINE RECORD: the moment the north-american slate is first computed for the day,
  // fire recordTodaysBoard so the registry gets populated immediately. This eliminates
  // the race window where a daily cron might run after games have already started — at
  // which point the integrity guard refuses to post-record. Fire-and-forget so the
  // user's slate response doesn't wait on recording I/O. Already-recorded picks dedupe
  // safely, so this is idempotent across multiple slate generations.
  if (board === 'north-american' && hasDatabase()) {
    void (async () => {
      try {
        const { recordTodaysBoard } = await import('@/services/recordBoardService');
        await recordTodaysBoard();
      } catch (err) {
        console.error('[dailyBoardCache] inline record failed', err);
      }
    })();
  }

  return result;
}
