import Link from "next/link";
import Image from "next/image";
import {
  ArrowRight, Trophy, Target, Zap, ShieldAlert, BarChart3,
  Activity, Globe, ShieldCheck, TrendingUp, Cpu, Timer, LineChart,
  Flame, Crosshair, Dumbbell, Gauge
} from "lucide-react";
import { LiveScoreBoard } from "@/components/LiveScoreBoard";
import { RecordDashboard } from "@/components/RecordDashboard";
import { organizationJsonLd, websiteJsonLd, faqJsonLd } from "@/lib/seo";

// Homepage FAQ — answers to the top searches people land on us with. Both rendered as
// visible HTML (so users see them) AND fed to Google as FAQPage JSON-LD for rich results.
const HOMEPAGE_FAQS = [
  {
    question: "Are HIMOTHY's picks free?",
    answer: "Yes — every pick on the daily board is free to view, including the Grand Slam, Pressure Pack, VIP 4-Pack, $10 Parlay Plan, Power 20 stack, Asleep Picks, Tonight's Edges, and Hot Tendencies. Real plays, real reasons, no paywall on the picks themselves."
  },
  {
    question: "How does HIMOTHY pick games?",
    answer: "Every pick is generated by a research engine that pulls real-line data from multiple sportsbooks, computes each team's last-10 ATS and Over/Under tendencies, and compares the projected total or margin to tonight's posted line. Picks only post when the math shows a real edge (0.7+ points on totals, 1.5+ on spreads). Otherwise the system says 'stay away' rather than force a play."
  },
  {
    question: "What sports does HIMOTHY cover?",
    answer: "NBA, NFL, MLB, NHL, WNBA, college basketball, college football, college baseball, UFC, tennis (ATP/WTA), golf (PGA/LIV), F1/NASCAR/IndyCar, soccer (EPL/La Liga/Bundesliga/Serie A/Champions League/MLS/Liga MX), rugby (NRL), AFL, and KBO baseball. Every league on Hard Rock Bet's main menu, every day."
  },
  {
    question: "What's the verified record?",
    answer: "Every pick the system has ever posted is graded against the official result and stored in a public registry. The full verified record — wins, losses, win rate by category, win rate by odds bucket, parlay performance by leg count — lives at /stats. Honest record from day one, no fake history."
  },
  {
    question: "What's an 'Asleep Pick'?",
    answer: "An Asleep Pick is a play from a lesser-watched league where sportsbooks haven't priced as tightly — NCAA Baseball, KBO, AFL, rugby NRL, Brazil Serie A, lower European leagues. These markets are softer because less money bets them, which means real edges live there. Our engine flags them on a dedicated tile so the chalk-heavy mainstream slate doesn't drown them out."
  },
  {
    question: "How big can a moneyline pick be?",
    answer: "No single moneyline pick on this site is priced steeper than -185. Heavier chalk pays too little to be worth a unit bet — a -300 favorite only pays $33 on a $100 bet, and one loss erases three wins. For parlays (Power 20 / Power 10), legs are capped at -450 maximum. Same reason: heavier chalk drags the parlay payout to nothing."
  },
];

export default function Home() {
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });

  return (
    <div className="min-h-screen bg-background text-white pb-24 premium-gradient selection:bg-primary/30">
      {/* SEO: SportsOrganization + WebSite + FAQ structured data so Google understands what we are AND can render expandable rich results in search */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd()) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd()) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd(HOMEPAGE_FAQS)) }} />
      {/* 1. Command Header */}
      <header className="px-6 lg:px-12 py-5 border-b border-white/5 bg-black/40 backdrop-blur-2xl sticky top-0 z-50 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="relative">
            <Image src="/logo-badge.png" alt="HIMOTHY PLAYS AND PARLAYS" width={52} height={52} className="rounded-full border border-primary/40 himo-glow" />
            <div className="absolute -bottom-1 -right-1 w-4 h-4 bg-emerald-500 rounded-full border-2 border-black animate-pulse" />
          </div>
          <div className="flex flex-col">
            <h1 className="text-lg font-black tracking-tight leading-none uppercase">
              HIMOTHY <span className="text-primary italic">PLAYS &amp; PARLAYS</span>
            </h1>
            <div className="flex items-center gap-2 mt-1">
               <span className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em]">Daily Picks · Parlays · VIP</span>
            </div>
          </div>
        </div>
        
        <nav className="hidden xl:flex items-center gap-10 text-[11px] font-black uppercase tracking-[0.2em] text-white/50">
          <Link href="/picks" className="hover:text-primary transition-all flex items-center gap-2 text-white">
            <Target className="w-3.5 h-3.5" /> Market Archive
          </Link>
          <Link href="/results" className="hover:text-primary transition-all flex items-center gap-2">
            <LineChart className="w-3.5 h-3.5" /> Performance
          </Link>
          <Link href="/live-sports-board" className="hover:text-primary transition-all flex items-center gap-2">
            <Activity className="w-3.5 h-3.5" /> Live Engine
          </Link>
        </nav>

        <div className="flex items-center gap-8">
          <div className="hidden md:flex flex-col items-end">
             <span className="text-[10px] font-black text-primary uppercase tracking-widest leading-none mb-1">Today's Board</span>
             <span className="text-[11px] font-bold text-emerald-400 flex items-center gap-1.5">
               <Cpu className="w-3 h-3" /> Live &amp; Updating
             </span>
          </div>
          <Link href="/pricing" className="bg-primary hover:bg-white text-black px-6 py-2.5 rounded-full font-black text-[11px] uppercase tracking-widest transition-all himo-glow transform hover:scale-105">
            Get Access
          </Link>
        </div>
      </header>

      <main className="flex-1">
        {/* 2. Hero Command Center */}
        <section className="relative px-6 lg:px-12 pt-12 pb-24 overflow-hidden">
          <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary/10 blur-[150px] -z-10 rounded-full" />
          
          <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-12 xl:col-span-7 flex flex-col gap-6">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 w-fit">
                <Timer className="w-4 h-4 text-primary" />
                <span className="text-[10px] font-black uppercase tracking-widest text-white/70">Today's Board — {today}</span>
              </div>
              <h2 className="text-5xl sm:text-6xl md:text-8xl font-black uppercase tracking-tighter leading-[0.9]">
                HIMOTHY <br />
                <span className="text-primary italic">Plays &amp; Parlays.</span>
              </h2>
              <p className="text-xl text-white/60 max-w-2xl leading-relaxed font-medium">
                Daily VIP picks, the Grand Slam, the 2-Pick Pressure Pack, and the $10 Parlay Plan.
                Every play comes with a clear reason why we like it.
                <span className="text-white"> No fluff. Just winners.</span>
              </p>

              <div className="flex flex-wrap gap-4 mt-4">
                <Link href="/picks" className="px-8 py-4 bg-primary text-black font-black uppercase text-xs tracking-widest rounded-2xl hover:bg-white transition-all flex items-center gap-3 group himo-glow">
                  See Today's Picks <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </Link>
                <div className="px-8 py-4 bg-white/5 border border-white/10 font-black uppercase text-xs tracking-widest rounded-2xl flex items-center gap-3">
                  <Activity className="w-4 h-4 text-emerald-500" />
                  Live Board Active
                </div>
              </div>
            </div>

            <div className="lg:col-span-12 xl:col-span-5 relative">
               <div className="glass-morphism rounded-3xl p-6 border-white/10 relative z-10 himo-glow">
                  <div className="flex items-center justify-between mb-6 border-b border-white/5 pb-4">
                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-white/40">Real-Time Core Metrics</h3>
                    <span className="text-[9px] font-bold text-emerald-400 px-2 py-0.5 rounded border border-emerald-400/20 bg-emerald-400/5 uppercase">Global Sync</span>
                  </div>
                  <RecordDashboard />
               </div>
               <div className="absolute -top-10 -right-10 w-40 h-40 bg-primary/20 blur-3xl -z-10 rounded-full" />
            </div>
          </div>
        </section>

        {/* 3. The Feed Section (Live Scoreboard) */}
        <section className="px-6 lg:px-12 py-16 md:py-24 bg-white/[0.02] border-y border-white/5">
           <div className="max-w-7xl mx-auto flex flex-col gap-8 md:gap-12">
              <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <div className="flex flex-col gap-3">
                  <span className="text-primary font-black uppercase text-[10px] tracking-[0.3em]">Live Feed Aggregate</span>
                  <h2 className="text-4xl font-black uppercase tracking-tight">Current Market <span className="text-white/40">Status</span></h2>
                </div>
                <Link href="/live-sports-board" className="text-xs font-black uppercase tracking-widest border-b border-primary/40 pb-1 hover:border-primary transition-all">
                  Open Engine Hub
                </Link>
              </div>

              <LiveScoreBoard />
           </div>
        </section>

        {/* 4. The HIMOTHY Packages */}
        <section className="px-6 lg:px-12 py-20 md:py-32 bg-background">
           <div className="max-w-7xl mx-auto">
              <div className="mb-12 md:mb-20 text-center flex flex-col items-center">
                 <Trophy className="w-12 h-12 text-primary mb-6" />
                 <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tight mb-4">The HIMOTHY <span className="text-primary italic">Packages</span></h2>
                 <p className="text-white/40 max-w-xl text-lg font-medium">Clarity, structure, and confidence every single day. Every play falls under one of these packages.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                 {/* Grand Slam */}
                  <Link href="/grand-slam" className="group glass-morphism rounded-3xl p-6 md:p-10 hover:border-primary transition-all flex flex-col h-full bg-gradient-to-br from-primary/[0.08] to-transparent">
                    <div className="flex items-start justify-between mb-8">
                       <Trophy className="w-14 h-14 text-primary group-hover:scale-110 transition-transform" />
                       <div className="flex flex-col items-end">
                          <span className="text-[10px] font-black uppercase tracking-widest bg-primary text-black px-4 py-1 rounded-full mb-2">Top Conviction</span>
                          <span className="text-[9px] font-bold text-white/40 uppercase">1-Pick</span>
                       </div>
                    </div>
                    <h3 className="text-3xl font-black uppercase mb-4 tracking-tight">HIMOTHY 1-Pick Grand Slam</h3>
                    <p className="text-white/50 text-sm leading-relaxed mb-10 font-medium">
                       The strongest play of the day. Only comes out when we really feel it — our highest-confidence single pick. When it drops, it means everything it always has.
                    </p>
                    <div className="mt-auto pt-8 border-t border-white/5 flex items-center justify-between">
                       <div className="flex flex-col">
                          <span className="text-[9px] font-black text-primary uppercase mb-1">Confidence</span>
                          <span className="text-lg font-black tracking-widest">ELITE</span>
                       </div>
                       <ArrowRight className="w-6 h-6 text-white group-hover:translate-x-2 transition-transform" />
                    </div>
                 </Link>

                 {/* Pressure Pack */}
                 <Link href="/pressure-pack" className="group glass-morphism rounded-3xl p-6 md:p-10 hover:border-primary transition-all flex flex-col h-full">
                    <div className="flex items-start justify-between mb-8">
                       <Zap className="w-14 h-14 text-primary group-hover:scale-110 transition-transform" />
                       <div className="flex flex-col items-end">
                          <span className="text-[10px] font-black uppercase tracking-widest bg-primary text-black px-4 py-1 rounded-full mb-2">2-Pick</span>
                          <span className="text-[9px] font-bold text-white/40 uppercase">The HIMOTHY Bet</span>
                       </div>
                    </div>
                    <h3 className="text-3xl font-black uppercase mb-4 tracking-tight">HIMOTHY 2-Pick Pressure Pack</h3>
                    <p className="text-white/50 text-sm leading-relaxed mb-10 font-medium">
                       Our 2 strongest plays of the day. If we're applying pressure, it's here — and when it's time to hammer, the HIMOTHY BET drops in this section only.
                    </p>
                    <div className="mt-auto pt-8 border-t border-white/5 flex items-center justify-between">
                       <div className="flex flex-col">
                          <span className="text-[9px] font-black text-primary uppercase mb-1">When We Hammer</span>
                          <span className="text-lg font-black tracking-widest">PRESSURE</span>
                       </div>
                       <ArrowRight className="w-6 h-6 text-white group-hover:translate-x-2 transition-transform" />
                    </div>
                 </Link>

                 {/* VIP 4-Pack */}
                 <Link href="/vip-picks" className="group glass-morphism rounded-3xl p-6 md:p-10 hover:border-primary transition-all flex flex-col h-full">
                    <div className="flex items-start justify-between mb-8">
                       <ShieldCheck className="w-14 h-14 text-primary group-hover:scale-110 transition-transform" />
                       <div className="flex flex-col items-end">
                          <span className="text-[10px] font-black uppercase tracking-widest bg-primary text-black px-4 py-1 rounded-full mb-2">4-Pack</span>
                          <span className="text-[9px] font-bold text-white/40 uppercase">The Foundation</span>
                       </div>
                    </div>
                    <h3 className="text-3xl font-black uppercase mb-4 tracking-tight">HIMOTHY VIP 4-Pack</h3>
                    <p className="text-white/50 text-sm leading-relaxed mb-10 font-medium">
                       Our daily 4-play package — structured, sharp picks we ride with daily. This is your foundation. Clean action, consistent value.
                    </p>
                    <div className="mt-auto pt-8 border-t border-white/5 flex items-center justify-between">
                       <div className="flex flex-col">
                          <span className="text-[9px] font-black text-primary uppercase mb-1">Daily</span>
                          <span className="text-lg font-black tracking-widest">FOUNDATION</span>
                       </div>
                       <ArrowRight className="w-6 h-6 text-white group-hover:translate-x-2 transition-transform" />
                    </div>
                 </Link>
              </div>

              {/* $10 Parlay Plan — full-width feature */}
              <Link href="/parlay-plan" className="mt-8 group glass-morphism rounded-3xl p-6 md:p-10 hover:border-primary transition-all flex flex-col md:flex-row md:items-center justify-between gap-6 bg-gradient-to-r from-primary/[0.06] to-transparent">
                 <div className="flex items-start gap-6">
                    <BarChart3 className="w-14 h-14 text-primary shrink-0 group-hover:scale-110 transition-transform" />
                    <div>
                       <h3 className="text-3xl font-black uppercase mb-2 tracking-tight">$10 Parlay Plan</h3>
                       <p className="text-white/50 text-sm leading-relaxed font-medium max-w-2xl">
                          For the flip chasers — run it daily. Built for those who love the risk, the thrill, and the chance to turn $10 into a whole move. Strategic parlays, not wild guesses.
                       </p>
                    </div>
                 </div>
                 <ArrowRight className="w-7 h-7 text-white group-hover:translate-x-2 transition-transform shrink-0" />
              </Link>

              {/* Edge tools — products built on top of the picks themselves */}
              <div className="mt-12">
                 <div className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-4 text-center">Edge Tools — Where the Sharp Money Lives</div>
                 <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {[
                      { label: "Asleep Picks", icon: Flame, href: "/asleep", sub: "Quiet markets" },
                      { label: "Tonight's Edges", icon: TrendingUp, href: "/edges", sub: "Top signals" },
                      { label: "Hot Tendencies", icon: Crosshair, href: "/trends", sub: "ATS & O/U" },
                      { label: "Value Plays", icon: Target, href: "/value", sub: "+EV vs true line" },
                    ].map((pkg, i) => (
                       <Link key={i} href={pkg.href} className="glass-morphism rounded-2xl p-4 border-white/5 hover:border-amber-400/40 transition-all flex flex-col gap-2 group">
                          <div className="flex items-center justify-between">
                            <pkg.icon className="w-7 h-7 text-amber-400" />
                            <ArrowRight className="w-4 h-4 opacity-40 group-hover:opacity-100 transition-all" />
                          </div>
                          <div>
                            <h4 className="font-black uppercase text-[11px] tracking-widest leading-tight">{pkg.label}</h4>
                            <div className="text-[10px] text-white/40 mt-0.5">{pkg.sub}</div>
                          </div>
                       </Link>
                    ))}
                 </div>
              </div>

              {/* Sport categories — every board Hard Rock-style on its own page */}
              <div className="mt-10">
                 <div className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-4 text-center">Every Sport, Every Edge</div>
                 <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {[
                      { label: "NBA", icon: Trophy, href: "/nba-picks-today" },
                      { label: "MLB", icon: Target, href: "/mlb-picks" },
                      { label: "MLB F5", icon: Target, href: "/mlb-f5-picks" },
                      { label: "WNBA Props", icon: Target, href: "/wnba-player-props" },
                      { label: "NCAA Hoops", icon: Trophy, href: "/ncaa-basketball-picks" },
                      { label: "KBO", icon: Target, href: "/kbo-picks-today" },
                      { label: "Soccer", icon: Globe, href: "/picks?board=soccer" },
                      { label: "Tennis", icon: Target, href: "/picks?board=tennis" },
                      { label: "UFC / Boxing", icon: Dumbbell, href: "/picks?board=combat" },
                      { label: "Golf", icon: Trophy, href: "/picks?board=individual" },
                      { label: "Racing", icon: Gauge, href: "/picks?board=racing" },
                      { label: "Best Parlays", icon: BarChart3, href: "/best-parlay-picks" },
                      { label: "Missouri", icon: ShieldCheck, href: "/missouri-sports-picks" },
                      { label: "Global", icon: ShieldCheck, href: "/picks?board=global" },
                      { label: "Hailmary", icon: Zap, href: "/hailmary" },
                    ].map((pkg, i) => (
                       <Link key={i} href={pkg.href} className="glass-morphism rounded-2xl p-4 border-white/5 hover:border-primary/40 transition-all flex items-center justify-between group">
                          <div className="flex items-center gap-3">
                           <pkg.icon className="w-7 h-7 text-primary" />
                           <h4 className="font-black uppercase text-[11px] tracking-widest leading-none">{pkg.label}</h4>
                          </div>
                          <ArrowRight className="w-4 h-4 opacity-40 group-hover:opacity-100 transition-all" />
                       </Link>
                    ))}
                 </div>
              </div>
           </div>
        </section>

        {/* 4b. Join Subscription CTA */}
        <section className="px-6 lg:px-12 py-20 bg-white/[0.02] border-y border-white/5">
           <div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center gap-10">
              <Image src="/promo-join.png" alt="Join HIMOTHY Plays and Parlays" width={360} height={360} className="rounded-3xl border border-primary/20 himo-glow w-full max-w-[300px] md:max-w-[340px]" />
              <div className="flex flex-col gap-5 text-center md:text-left">
                 <h2 className="text-4xl md:text-5xl font-black uppercase tracking-tight">Join <span className="text-primary italic">Subscription</span> Today</h2>
                 <p className="text-white/50 text-lg font-medium max-w-xl">Lock in daily VIP picks, the Pressure Pack, the Grand Slam, and the $10 Parlay Plan. Start winning with HIMOTHY.</p>
                 <Link href="/pricing" className="bg-primary hover:bg-white text-black px-8 py-4 rounded-2xl font-black text-xs uppercase tracking-widest transition-all himo-glow w-fit mx-auto md:mx-0 flex items-center gap-3 group">
                    Get Access <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                 </Link>
              </div>
           </div>
        </section>

        {/* Visible FAQ — mirrored to FAQPage JSON-LD above so Google can render rich
            results, but also a real human-readable section so users land on a satisfying
            answer instead of bouncing back to search. */}
        <section className="px-6 lg:px-12 py-16 border-t border-white/5">
          <div className="max-w-4xl mx-auto">
            <div className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-2">Frequently Asked</div>
            <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tight mb-8">Questions, Answered Straight</h2>
            <div className="space-y-4">
              {HOMEPAGE_FAQS.map((faq, i) => (
                <details key={i} className="group rounded-2xl border border-white/10 bg-white/[0.02] p-5 open:bg-white/[0.04] transition">
                  <summary className="cursor-pointer list-none flex items-center justify-between gap-4 text-base font-black text-white">
                    <span>{faq.question}</span>
                    <span className="text-primary text-xl shrink-0 transition-transform group-open:rotate-45">+</span>
                  </summary>
                  <p className="mt-4 text-white/65 leading-relaxed text-sm">{faq.answer}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* 5. Footer Disclaimer */}
        <footer className="px-6 lg:px-12 py-12 border-t border-white/5 bg-background/80 flex flex-col md:flex-row justify-between gap-12">
            <div className="flex flex-col gap-4 max-w-sm">
                <div className="flex items-center gap-3">
                   <Image src="/logo-badge.png" alt="HIMOTHY PLAYS AND PARLAYS" width={40} height={40} className="rounded-full border border-primary/40" />
                   <h5 className="text-[11px] font-black uppercase tracking-[0.2em] text-primary">HIMOTHY Plays &amp; Parlays</h5>
                </div>
                <p className="text-[11px] text-white/40 leading-relaxed font-bold">
                   All picks are provided for informational and entertainment purposes. We do not facilitate gambling. Must be 21+. Play responsibly.
                </p>
            </div>

            <div className="flex flex-wrap gap-8">
               <div className="flex flex-col gap-3">
                  <span className="text-[10px] font-black text-white/40 uppercase tracking-widest">Picks</span>
                  <div className="flex flex-col gap-2 text-xs font-bold text-white/60">
                     <Link href="/picks" className="hover:text-primary transition-all">Today's Picks</Link>
                     <Link href="/results" className="hover:text-primary transition-all">Results &amp; Record</Link>
                     <Link href="/pricing" className="hover:text-primary transition-all">Get Access</Link>
                  </div>
               </div>
               <div className="flex flex-col gap-3">
                  <span className="text-[10px] font-black text-white/40 uppercase tracking-widest">Legal</span>
                  <div className="flex flex-col gap-2 text-xs font-bold text-white/60">
                     <Link href="/privacy" className="hover:text-primary transition-all">Privacy</Link>
                     <Link href="/terms" className="hover:text-primary transition-all">Terms</Link>
                     <Link href="/contact" className="hover:text-primary transition-all">Contact</Link>
                  </div>
               </div>
            </div>
        </footer>
      </main>
    </div>
  );
}
