import Image from "next/image";
import Link from "next/link";

// Named-expert byline on every pick page. Google's 2026 YMYL/E-E-A-T raters explicitly
// look for credentialed authors on betting + finance content — 75% of top-ranking iGaming
// pages now have visible author bios. Without this, unsigned content gets downranked
// regardless of how good the analysis is.
//
// All picks roll up under the HIMOTHY brand author for now. When a real human signs
// individual breakdowns, swap the name + bio per-pick by passing props.
interface Props {
  name?: string;
  role?: string;
  bio?: string;
}

export function AuthorByline({
  name = "HIMOTHY Research Desk",
  role = "Sports Analysis Team",
  bio = "Daily picks generated by HIMOTHY's research engine — real-line data from multiple sportsbooks, last-10 ATS and O/U tendencies, multi-book best-price consensus. Every pick is graded against the official result.",
}: Props) {
  return (
    <aside className="flex items-start gap-4 rounded-2xl border border-white/8 bg-white/[0.02] p-4">
      <Image
        src="/logo-badge.png"
        alt={`${name} avatar`}
        width={48}
        height={48}
        className="rounded-full border border-primary/40 shrink-0"
      />
      <div className="min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-sm font-black text-white">{name}</span>
          <span className="text-[10px] font-black uppercase tracking-widest text-primary">{role}</span>
        </div>
        <p className="mt-1 text-xs text-white/55 leading-relaxed">{bio}</p>
        <div className="mt-2 flex flex-wrap gap-3 text-[10px] font-black uppercase tracking-widest">
          <Link href="/stats" className="text-emerald-400 hover:text-emerald-300">Verified Record →</Link>
          <Link href="/how-it-works" className="text-white/40 hover:text-white">Methodology →</Link>
          <Link href="/about" className="text-white/40 hover:text-white">About the Desk →</Link>
        </div>
      </div>
    </aside>
  );
}
