import Link from "next/link";

// Evergreen sport-specific SEO content. Each block targets long-tail keywords ("nba picks
// today", "mlb run line picks", "best parlay strategy") while being substantial enough
// (300-500 words) that Google treats the page as having real content, not just a feed
// of dynamic data. Internal links pass authority to /trends, /asleep, /edges.

const cardCls = "rounded-2xl border border-white/8 bg-white/[0.02] p-5 md:p-6";

function CrossLinks() {
  return (
    <div className="mt-6 flex flex-wrap gap-2 not-prose">
      <Link href="/edges" className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-emerald-400 hover:bg-emerald-400/20 transition">Tonight's Edges</Link>
      <Link href="/trends" className="rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-amber-400 hover:bg-amber-400/20 transition">Hot Tendencies</Link>
      <Link href="/asleep" className="rounded-full border border-orange-400/30 bg-orange-400/10 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-orange-400 hover:bg-orange-400/20 transition">Sleeper Picks</Link>
      <Link href="/value" className="rounded-full border border-sky-400/30 bg-sky-400/10 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-sky-400 hover:bg-sky-400/20 transition">Value Plays</Link>
      <Link href="/stats" className="rounded-full border border-white/15 bg-white/[0.04] px-3 py-1 text-[11px] font-black uppercase tracking-widest text-white/60 hover:bg-white/[0.08] transition">Verified Record</Link>
    </div>
  );
}

export function NbaSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">Tonight's NBA Picks — Built On Real Numbers</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        Every NBA play on this page is generated by our deep-research engine, which scans tonight's slate for spread, moneyline, total, and player prop edges across every game on the board. We don't post a side because two analysts on a podcast like it — we post it because the math says the line is off, the recent ATS tendency points that way, and the multi-book consensus confirms it.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">What we look at for every NBA pick</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Pace is the biggest variable nobody talks about. A high-pace team like the Pacers or Nuggets playing a low-pace team like the Celtics or Magic produces a total that's almost never priced correctly. We pull each team's last-10 average game total, compute the midpoint, and only post the over/under when the gap with the posted line is real (0.7+ points of edge). Below that we say <strong>stay away</strong> instead of forcing a coin flip.
      </p>
      <p className="text-white/70 leading-relaxed mb-3">
        Spread picks lean on the same model. We compute the projected home margin from each team's last-10 average margin, adjust for a league-standard 2.5-point home-court bump (1.5 for road favorites), and compare to tonight's number. The pick lands as a <Link href="/edges" className="text-emerald-400 underline">value edge</Link> when our model differs from the line by 1.5+ points.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">NBA player props + alt lines</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        On every NBA pick page you'll see the alt-line ladder for points, rebounds, assists, and threes — multi-book best prices for each step. Sportsbooks price these soft, so the goal is to surface the cheapest line at the best book rather than just take the headline number. We also flag streaks (last-5 over/under counts) so you see whether a player is heating up before you bet the prop.
      </p>
      <p className="text-white/70 leading-relaxed">
        Want the sharpest reads only? <Link href="/edges" className="text-primary underline">Tonight's Edges</Link> filters to picks with real positive expected value vs. the consensus true line. <Link href="/trends" className="text-primary underline">Hot Tendencies</Link> surfaces teams 7-3 or better against the spread or total over their last 10. <Link href="/asleep" className="text-primary underline">Sleeper Picks</Link> covers WNBA + lesser leagues where books are softest.
      </p>
      <CrossLinks />
    </article>
  );
}

export function MlbSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">Today's MLB Picks — Run Lines, Totals, F5 & NRFI</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        MLB is the densest betting market of the year: 162 games per team, fresh data every day, and a starting pitcher matchup that drives 70% of the total. Every MLB pick on this page is built on the matchup — opposing starter ERA, recent runs allowed, bullpen rest, park factor, weather, and each team's last-10 average game total. Heavy moneyline favorites (steeper than -185) get converted to a run-line play to avoid the juice trap.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">F5 (First 5 Innings) — the sharp angle</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        F5 markets isolate the starting pitchers and remove bullpen variance — the single biggest source of noise in MLB betting. If your pitcher is good and theirs is shaky, the F5 line gives you a cleaner version of the game-long total or moneyline at a much smaller juice. Every MLB pick page on this site surfaces the F5 total, spread, and moneyline with multi-book best prices.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">NRFI — No Runs First Inning</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        The NRFI prop tracks the probability that neither team scores in the top OR bottom of the 1st. Our model weighs both probable starters' first-inning ERAs, recent NRFI hit rate, and lineup quality. NRFI is its own dedicated category on the picks board — straight plays, no parlays, only when both pitchers have a real shutout case.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Player props — strikeouts, hits, total bases, home runs</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        On the breakdown page for every MLB game you'll see alt-prop ladders for pitcher strikeouts, batter hits, total bases, and home runs. Multi-book best prices, recent-form streaks (over/under the line last 5 starts), and matchup notes. These markets are the softest sportsbooks offer — the math edges are bigger than you'd expect.
      </p>
      <p className="text-white/70 leading-relaxed">
        See the <Link href="/trends" className="text-primary underline">Hot Tendencies</Link> page for teams 7-3 or better ATS or to the over their last 10 games. Verified record at <Link href="/stats" className="text-primary underline">/stats</Link>.
      </p>
      <CrossLinks />
    </article>
  );
}

export function NcaaBasketballSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">College Basketball Picks Today — NCAAB Spread, Total & ML</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        College basketball is where the line inefficiencies live. Books can't price 350+ Division I teams as precisely as they price the NBA, so smaller programs, mid-majors, and back-end conference games carry real edges. Every NCAAB pick on this page is generated by our research engine: pace, opponent-adjusted offensive/defensive efficiency, home-court (a much bigger factor in college — 3.5 points vs. 2.5 in the NBA), and recent ATS tendency over the last 10.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Why college basketball totals move so much</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Pace is the single biggest variable in college hoops. A 70-possession team playing a 62-possession team almost always produces a total between the two — but books price toward the historical average, missing the matchup. We compute each team's last-10 average game total and surface the gap as a real <Link href="/edges" className="text-emerald-400 underline">edge</Link> when it's 0.7+ points off the posted line.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Conference tournaments and March Madness</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Bracket play is where the public floods one side and softens the other. Public-money tracking, sharp-money signals, and the bigger home-court advantage in conference tournament games (when applicable) all feed into our model. The system never forces a pick — when the tendency math cancels out, we say <strong>stay away</strong> rather than guess.
      </p>
      <p className="text-white/70 leading-relaxed">
        Looking for the quieter spots? <Link href="/asleep" className="text-orange-400 underline">Sleeper Picks</Link> highlights mid-major and lesser-watched conference games where books are softest. <Link href="/trends" className="text-amber-400 underline">Hot Tendencies</Link> surfaces teams 7-3 or better ATS over their last 10.
      </p>
      <CrossLinks />
    </article>
  );
}

export function ParlaySeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">Best Parlay Picks Today — Built On Math, Not Vibes</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        Most parlays lose because they stack heavy favorites at -300 or worse, where one upset wipes out months of action. Our parlay engine runs the opposite way: we cap every leg at -450 maximum, prioritize legs at -185 to +160 where the real money lives, and dedupe against the regular pick board so the parlay never overlaps with picks we've already posted as straights.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">The $10 Parlay Plan</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Our daily flagship parlay. 3-4 legs, all from today's analyzed slate, picked for correlation when possible. The $10 stake is designed to chase real payouts ($50-$250 range) without a stake that ruins your bankroll if it misses. <Link href="/parlay-plan" className="text-primary underline">See today's $10 Parlay Plan →</Link>
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Power 20 + Power 10 — heavy chalk stacks</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Two big-payout parlays generated daily from today's heavy-favorite slate. Power 20 stacks 20 chalk legs for moonshot payouts; Power 10 is the safer 10-leg version. Every leg is capped at -450, every leg comes from a different game (correlation-aware), and the legs never overlap with picks already on the regular board. Available on the picks page under the Power 20 tab.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Same Game Parlay (SGP)</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        On every pick breakdown page you'll see SGP-friendly props for that game — picks that correlate positively (QB pass yards + WR receiving yards, or pitcher strikeouts + game under) so the parlay payout reflects a real edge instead of pure leverage.
      </p>
      <p className="text-white/70 leading-relaxed">
        The full <Link href="/stats" className="text-primary underline">verified record</Link> tracks parlay performance by leg count and theme — so you can see exactly how often each parlay format has cashed since the system went live.
      </p>
      <CrossLinks />
    </article>
  );
}

export function WnbaPropsSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">WNBA Player Props Today — Points, Rebounds, Assists, Threes</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        WNBA betting has exploded in 2026 — audience is up, lines have tightened, and player prop volume is finally rivaling NBA on the per-game basis. But most picks sites still treat the WNBA as an afterthought, posting two prop picks a night and calling it covered. We don't. Every WNBA game on tonight's slate gets the same treatment as an NBA matchup: alt-prop ladders for points, rebounds, assists, and threes — multi-book best prices for every step.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Why WNBA props are softer than NBA</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Sportsbooks have less data to model WNBA players than NBA players. That means alt-line ladders price imprecisely, and steps a half-line off the headline number frequently sit at +120 or better when the player is hitting consistently. Our system surfaces every step at every book so you can find the cheapest entry for the side our model likes — instead of taking whatever DraftKings posts on the main line.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Caitlin Clark, A&apos;ja Wilson, Sabrina Ionescu — the volume props</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Star WNBA players drive most prop interest. Clark&apos;s threes/assists ladders, Wilson&apos;s points/rebounds, Ionescu&apos;s threes — all are markets where the public hammers one side and the line moves accordingly. Our model uses last-5 game streak data (how many times the player has gone over/under recently), recent-form averages, and matchup-based pace adjustments to land on the alt-line step with the real edge.
      </p>
      <p className="text-white/70 leading-relaxed">
        Browse <Link href="/picks?board=north-american" className="text-primary underline">tonight&apos;s WNBA picks</Link> alongside the NBA, NHL, MLB slate, or jump to <Link href="/asleep" className="text-orange-400 underline">Sleeper Picks</Link> for the lesser-watched WNBA matchups where books are softest.
      </p>
      <CrossLinks />
    </article>
  );
}

export function KboSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">KBO Picks Today — Korean Baseball Plays for US Bettors</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        KBO (Korea Baseball Organization) plays games at 5:30 AM ET on weekdays and earlier on weekends — perfect for US night-owl bettors who want action after MLB wraps. The market is dramatically softer than MLB because US books carry far less liquidity on Korean baseball, which means line inefficiencies stay open longer. Every KBO game in season gets the same engine treatment: pitcher matchup, last-10 ATS, total tendency, multi-book best price.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Why KBO is one of the sharpest plays on the board</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        KBO totals are notoriously movable. The league averages more runs per game than MLB but with higher per-game variance — strong pitcher matchups produce 5-6 run games, weak pitcher matchups blow up to 14+. Books often set the total around the league average regardless of the matchup, leaving real edges on either Over or Under depending on the starters. Our system computes each team&apos;s last-10 average game total, compares to tonight&apos;s line, and flags BET / STAY AWAY based on the gap.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">KBO run line and moneyline</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Heavy KBO favorites often price at -240 or worse on the moneyline — too steep for a straight bet (our system caps ML picks at -185). For those games we convert to the run line at standard -110, where the value lives. Same approach as MLB: avoid the juice trap, get paid for being right.
      </p>
      <p className="text-white/70 leading-relaxed">
        KBO picks live in the <Link href="/asleep" className="text-orange-400 underline">Sleeper Picks</Link> tile on the main board — quieter markets where edges are bigger. <Link href="/trends" className="text-amber-400 underline">Hot Tendencies</Link> surfaces KBO teams 7-3 or better against the spread or total over their last 10.
      </p>
      <CrossLinks />
    </article>
  );
}

export function F5SeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">MLB F5 Picks — First 5 Innings Totals, Spread & Moneyline</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        First 5 innings (F5) markets are the sharpest baseball angle most bettors aren&apos;t using. They isolate the starting pitcher matchup and remove bullpen variance — the single biggest source of MLB betting noise. If your starter is good and theirs is shaky, the F5 line lets you bet that edge without worrying about a meltdown in the 7th inning.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">When to bet the F5 instead of the full game</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Three scenarios where F5 is the better play than the full-game total or moneyline:
      </p>
      <ul className="list-disc list-inside space-y-1.5 text-white/70 leading-relaxed mb-4">
        <li><strong>Heavy ML favorite</strong> — Full-game moneyline at -240 pays nothing; the F5 ML on the same favorite usually prices at -130 to -170, much better unit value.</li>
        <li><strong>Two aces matched up</strong> — Total locked at 7.5 because of the pitchers, but you trust the bats to wake up late. Take F5 Under, fade the full-game over.</li>
        <li><strong>One ace, one back-end starter</strong> — F5 favors the team with the ace, but the full game flips to a coin flip once both bullpens come in. F5 isolates the edge.</li>
      </ul>
      <h3 className="text-lg font-black text-white mt-5 mb-2">How we pick F5</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Every MLB pick breakdown page on this site surfaces the F5 total, spread, and moneyline with multi-book best prices. Lines are pulled from The Odds API every 15 minutes; we compare the consensus F5 total to each starter&apos;s recent first-5-inning ERA + opposing lineup quality and flag the strongest reads on the main MLB board.
      </p>
      <p className="text-white/70 leading-relaxed">
        See <Link href="/mlb-picks" className="text-primary underline">today&apos;s full MLB slate</Link>, or for the niche-but-related angle, check the <Link href="/nrfi" className="text-primary underline">NRFI (No Runs First Inning)</Link> picks — first-inning only, even sharper edge when both pitchers are first-inning specialists.
      </p>
      <CrossLinks />
    </article>
  );
}

export function MissouriSeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">Missouri Sports Picks — Best Daily Plays For MO Bettors</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        Missouri legalized sports betting in December 2025 — the 39th US state to do so. The Show-Me State&apos;s major operators (DraftKings, FanDuel, BetMGM, Caesars, and Fanatics) all launched in the first quarter of 2026. That means MO bettors finally have legal options after years of crossing state lines into Kansas or Illinois — and the search demand for &quot;missouri sports picks&quot; has exploded as new bettors look for daily plays.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Which sportsbooks are live in Missouri</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Every pick on this site shows the best price across DraftKings, FanDuel, BetMGM, Caesars, Fanatics, and BetRivers — the major operators with live Missouri licenses. The best price is rarely on the same book twice in a row; line-shopping across all six adds 1-3% to your long-term ROI without changing what you bet.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Missouri teams to bet — Cardinals, Royals, Chiefs, Blues</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Public money in Missouri leans hard on home teams. The Cardinals (MLB), Royals (MLB), Chiefs (NFL), and Blues (NHL) routinely see lines move 1-2 points before kickoff/first pitch when MO books start taking heavy action on the home side. That public pressure creates value on the opposite side — a classic contrarian angle. Our system flags these moves on the <Link href="/edges" className="text-emerald-400 underline">Tonight&apos;s Edges</Link> page when the math agrees.
      </p>
      <h3 className="text-lg font-black text-white mt-5 mb-2">Free Missouri picks every day</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Every pick on the daily board is free — no email signup, no paywall, no upsell. The Grand Slam, Pressure Pack, VIP 4-Pack, $10 Parlay Plan, and Sleeper Picks are all viewable. Verified record at <Link href="/stats" className="text-primary underline">/stats</Link>.
      </p>
      <p className="text-white/70 leading-relaxed">
        Browse <Link href="/picks" className="text-primary underline">tonight&apos;s full slate</Link>, or jump to a sport: <Link href="/mlb-picks" className="text-primary underline">MLB</Link>, <Link href="/nba-picks-today" className="text-primary underline">NBA</Link>, <Link href="/best-parlay-picks" className="text-primary underline">parlays</Link>.
      </p>
      <CrossLinks />
    </article>
  );
}

export function SportsPicksTodaySeoContent() {
  return (
    <article className={cardCls}>
      <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-3">Sports Picks Today — Every Sport, Every Market, Real Edge</h2>
      <p className="text-white/70 leading-relaxed mb-4">
        This is the full board: tonight's slate across every Hard Rock-style sport — NBA, NFL, MLB, NHL, WNBA, college football, college basketball, UFC, tennis, golf, soccer, plus international markets like AFL, rugby, cricket, and Brazil Serie A. Every pick is generated by the same research engine, with the same rules:
      </p>
      <ul className="list-disc list-inside space-y-2 text-white/70 leading-relaxed mb-4">
        <li><strong>No moneyline picks steeper than -185</strong> on straight plays — they pay too little to be worth the risk.</li>
        <li><strong>Parlay legs capped at -450</strong> — anything heavier kills the parlay payout.</li>
        <li><strong>Tendency math on every pick</strong> — predicted total or margin computed from each team's last-10 averages, compared to tonight's line, with a clear BET / STAY AWAY / PASS recommendation.</li>
        <li><strong>Today-only slate</strong> — no tomorrow's games padding the board, no future cards mixed in. ET-anchored to tonight's date only.</li>
        <li><strong>Multi-book best price</strong> on every pick so you can line-shop without leaving the page.</li>
      </ul>
      <h3 className="text-lg font-black text-white mt-5 mb-2">How we find the edges</h3>
      <p className="text-white/70 leading-relaxed mb-3">
        Real-line value (when our best price beats the consensus true line), strong ATS or Over/Under tendency (7-3 or better over the last 10), sharp-money alignment (where the books are taking heavy action on our side), and asleep-market edges (lesser-watched leagues where books haven't priced as tightly). All four show up on the <Link href="/edges" className="text-emerald-400 underline">Tonight's Edges</Link> page.
      </p>
      <p className="text-white/70 leading-relaxed">
        The full verified record lives at <Link href="/stats" className="text-primary underline">/stats</Link> — every graded pick since day one, broken out by product (Grand Slam, Pressure Pack, VIP 4-Pack, Parlay Plan), by odds bucket, and by parlay leg count.
      </p>
      <CrossLinks />
    </article>
  );
}
